login: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  encoding: unicode

development:
    database: iwa_development
    <<: *default

test:
   database: iwa_test
   <<: *default

production:
  database: iwa_production
  <<: *default
